MYSQL_CREDENTIALS:
  MYSQL_DATABASE_USER: root # input your username (root)
  MYSQL_DATABASE_PASSWORD: sid3502 #input your password
  MYSQL_DATABASE_DB: user_db #input your database name
  MYSQL_DATABASE_HOST: localhost #input your host (localhost)
  MYSQL_DATABASE_PORT: 3306 #input your port (3306)




